spring.datasource.url=jdbc:hsqldb:file:~/Projetos/dados/apclinic/apclinic;sql.syntax_pgs=true;hsqldb.write_delay=false;;shutdown=true;
spring.datasource.username=sa
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.datasource.hikari.pool-name=apclinic-pool

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.use-new-id-generator-mappings=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.open-in-view=false

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.mvc.favicon.enabled=false

spring.output.ansi.enabled=always

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

logging.pattern.console=%white(%d{"dd/MM/yyyy HH:mm:ss,SSS"}) %cyan(APClinic) %green(%X{req.remoteHost}) %highlight(%-5level %m%n)
logging.level.com.github.andrepenteado=TRACE

server.error.whitelabel.enabled=false